home:
    path: /
    defaults: {_controller: App\Controller\HomeController:homeAction}

newPost:
    path: /newPost
    defaults: {_controller: App\Controller\PostController:newPostAction}

listPosts:
    path: /listPosts
    defaults: {_controller: App\Controller\PostController:listPostsAction}

contact:
    path: /contact
    defaults: {_controller: App\Controller\ContactController:contactAction}

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

