home:
    path: /
    defaults: {_controller: App\Controller\HomeController:homeAction}

newPost:
    path: /newPost
    defaults: {_controller: App\Controller\PostController:newPostAction}

listPosts_paginated:
    path: /listPosts/{page}
    defaults: {_controller: App\Controller\PostController:listPostsAction, page: 1}
    requirements:
        page: '\d+'

post:
    path: post/{id}
    defaults: {_controller: App\Controller\PostController:singlePost}
    requirements:
        id: '\d+'

contact:
    path: /contact
    defaults: {_controller: App\Controller\ContactController:contactAction}

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

